export const countries = [
  "United States of America",
  "United Kingdom of Great Britain and Northern Ireland",
  "Canada",
  "Norway",
  "Uzbekistan",
  "Serbia",
  "Poland",
  "Philippines",
  "Bulgaria",
  "Switzerland",
  "India",
  "Germany",
  "Ireland",
  "Italy",
  "Ukraine",
  "Australia",
  "Brazil",
  "Japan",
  "Austria",
  "Iran, Islamic Republic of...",
  "France",
  "Saudi Arabia",
  "Romania",
  "Turkey",
  "Nepal",
  "Algeria",
  "Sweden",
  "Netherlands",
  "Croatia",
  "Pakistan",
  "Czech Republic",
  "Republic of North Macedonia",
  "Finland",
  "Slovakia",
  "Russian Federation",
  "Greece",
  "Israel",
  "Belgium",
  "Mexico",
  "United Republic of Tanzania",
  "Hungary",
  "Argentina",
  "Portugal",
  "Sri Lanka",
  "Latvia",
  "China",
  "Singapore",
  "Lebanon",
  "Spain",
  "South Africa",
  "Lithuania",
  "Viet Nam",
  "Dominican Republic",
  "Indonesia",
  "Kosovo",
  "Morocco",
  "Taiwan",
  "Georgia",
  "San Marino",
  "Tunisia",
  "Bangladesh",
  "Nigeria",
  "Liechtenstein",
  "Denmark",
  "Ecuador",
  "Malaysia",
  "Albania",
  "Azerbaijan",
  "Chile",
  "Ghana",
  "Peru",
  "Bolivia",
  "Egypt",
  "Luxembourg",
  "Montenegro",
  "Cyprus",
  "Paraguay",
  "Kazakhstan",
  "Slovenia",
  "Jordan",
  "Venezuela, Bolivarian Republic of...",
  "Costa Rica",
  "Jamaica",
  "Thailand",
  "Nicaragua",
  "Myanmar",
  "Republic of Korea",
  "Rwanda",
  "Bosnia and Herzegovina",
  "Benin",
  "El Salvador",
  "Zimbabwe",
  "Afghanistan",
  "Estonia",
  "Malta",
  "Uruguay",
  "Belarus",
  "Colombia",
  "Republic of Moldova",
  "Isle of Man",
  "Nomadic",
  "New Zealand",
  "Palestine",
  "Armenia",
  "United Arab Emirates",
  "Maldives",
  "Ethiopia",
  "Fiji",
  "Guatemala",
  "Uganda",
  "Turkmenistan",
  "Mauritius",
  "Kenya",
  "Cuba",
  "Gabon",
  "Bahamas",
  "South Korea",
  "Iceland",
  "Honduras",
  "Hong Kong (S.A.R.)",
  "Lao People's Democratic Republic",
  "Mongolia",
  "Cambodia",
  "Madagascar",
  "Angola",
  "Democratic Republic of the Congo",
  "Syrian Arab Republic",
  "Iraq",
  "Namibia",
  "Senegal",
  "Kyrgyzstan",
  "Zambia",
  "Swaziland",
  "Côte d'Ivoire",
  "Kuwait",
  "Tajikistan",
  "Burundi",
  "Trinidad and Tobago",
  "Mauritania",
  "Sierra Leone",
  "Panama",
  "Somalia",
  "North Korea",
  "Dominica",
  "Guyana",
  "Togo",
  "Oman",
  "Barbados",
  "Andorra",
  "Democratic People's Republic of Korea",
  "Qatar",
  "Sudan",
  "Cameroon",
  "Papua New Guinea",
  "Bahrain",
  "Yemen",
  "Malawi",
  "Burkina Faso",
  "Congo, Republic of the...",
  "Botswana",
  "Guinea-Bissau",
  "Mozambique",
  "Central African Republic",
  "Equatorial Guinea",
  "Suriname",
  "Belize",
  "Libyan Arab Jamahiriya",
  "Cape Verde",
  "Brunei Darussalam",
  "Bhutan",
  "Guinea",
  "Niger",
  "Antigua and Barbuda",
  "Mali",
  "Samoa",
  "Lesotho",
  "Saint Kitts and Nevis",
  "Monaco",
  "Micronesia, Federated States of...",
  "Haiti",
  "Nauru",
  "Liberia",
  "Chad",
  "Djibouti",
  "Solomon Islands",
];
